### ISSUE TITLE
MxM Pre-Processor Composite Category Settings Extrapolate Check Box

### ISSUE THREAD

**Issue by HarebrainedDave** [Avindr/MxM-IssueTracking#1] opened 2019-12-10 01:39 UTC
Steps:
1. Open MxM Pre-Processor in Inspector
2. Open Composites animation list
3. Select Category Settings gear icon
4. Check Extrapolate

Results:
 - Extrapolate check box un-checks itself some random amount of time from immediately to a handful of seconds later.
- Individual animations are not set to Extrapolate
- This feature has worked correctly at least once but usually does not. Can not identify conditions to reliably reproduce.

Software Versions:
Unity - 2019.2.13f1
MxM v2.01

**Comment by Avindr** [comment] 2019-12-16 04:00
This issue is Unity version specific. 

Confirmed that it works fine on 2018.4. Testing on other versions in 2019.3x and 2019.2x to isolate the issue and find a solution.

**Comment by Avindr** [comment] 2019-12-16 05:05
After some minor changes, this feature appears to be working as intended in MxM v2.02.

Tested on the following versions if Unity:
- 2018.4
- 2019.2.14f1
- 2019.3.0f1

I am going to close this issue for now. If the issue arises again, first try updating to a newer version of Unity. If that does not resolve the issue I will open it again and investigate further.

**Closed by Avindr** 2019-12-16 05:05 UTC
Labels: bug
