### ISSUE TITLE
Suggestion - Pre-Processor association to Animation Data

### ISSUE THREAD

**Issue by Craigjw** [Avindr/MxM-IssueTracking#84] opened 2020-12-12 21:10 UTC
Can we have an association within the Pre-Processor to the animation data, so that we don't have to select the file manually each time we pre-process the animation data please.

**Comment by Craigjw** [comment] 2020-12-15 14:17
This could be done by having an object box with an association to the animData module, when pressed, it will just use the path of the animData to save it to disk, while saving the module reference to the preprocessor.  If the box is empty, then follow the current method for saving it.   This is would be a nice quality of life addition.

**Comment by Avindr** [comment] 2021-01-18 05:20
Interesting... this is already in the code but for some reason it isn't working anymore. I'll investigate and see if I can get it working again.

**Comment by Avindr** [comment] 2021-01-18 05:31
Looks like I was missing a line of code. 

This should now be working and will be available with MxM v2.2.8. You won't see the AnimData association on the inspector (unless you go debug mode) but it will now automatically associate with whatever AnimData it last pre-processed and the save option will take you straight to that path.

I don't want it to automatically use the path though without the user explicitly choosing the file to avoid accidental overwrite but at least now you won't have to navigate to the anim data every time.

**Comment by Craigjw** [comment] 2021-02-13 22:59
This doesn't work in v2.2.8.

When I select Pre-Process Animation Data from the pre-processor, it automatically chooses the default name of "MxMAnimData.asset".  If I have renamed this file to something more meaningful for my project, I have to reselect it.

**Comment by Avindr** [comment] 2021-02-15 01:02
Interesting. Is it at least taking you to the correct directory?

**Comment by Craigjw** [comment] 2021-02-15 19:39
I'm not sure about the directory, I've done a bit of testing on that myself can't verify it.  I will let you know if I find anything more.

**Comment by Avindr** [comment] 2021-02-17 06:41
![image](https://user-images.githubusercontent.com/29056263/108165760-d4fa0c00-713e-11eb-82b5-78d5390f30fa.png)

Made a slight change and it should be remembering the name now as well. I just need to do some checks to make sure the reference isn't getting lost when Unity restarts. 

I'll throw this in a hotfix on the discord channel.

**Comment by Avindr** [comment] 2021-02-17 06:44
I can confirm this is working in Unity 2018.4LTS (development build) so I'm going to include it in the hotfix. If it's not working in newer versions of Unity for some reason then I will revisit it for those specific versions next version update.

**Comment by Craigjw** [comment] 2021-02-17 14:41
This seems to work fine for me now.  Thank you.

**Comment by Avindr** [comment] 2021-02-18 13:01
Thanks I'll close this now.

**Closed by Avindr** 2021-02-18 13:01 UTC
Labels: Quality of Life, bug
