### ISSUE TITLE
Character gets stuck.

### ISSUE THREAD

**Issue by tadilj** [Avindr/MxM-IssueTracking#133] opened 2021-09-01 05:42 UTC
It seems that sometimes the character gets stuck.
>MxMAnimator
>RootMotion On

Phenomenon:
>The green arrow is fully extended, but the red one is not.
>I've tried various update rates.

Maybe it's because of this: 
>Perform a direction change to a direction close to directly behind.
>Less animation to turn right back?

I don't think this is a bug, it's probably a misconfiguration on my part.

Thank you very much.

**Comment by Avindr** [comment] 2021-11-16 06:13
After getting an example project to test this I found it was indeed caused by coverage issues with cut clips. The trajectory got so far extended beyond the current animation that the gap to jump was very large. I managed to fix this by improving the setup by adding 'RuntimeSplicing' to the plant and start animations. The 'TrajectoryBlending' option on the MxMAnimator can help also but too much of it will cause poor responsiveness. 

> I found a potential solution and hint to the origin of the problem here [#130 (comment)](https://github.com/Avindr/MxM-IssueTracking/issues/130#issuecomment-952790686)

I believe that issue 130 that you submitted is likely a very different issue altogether even though the outcome may appear similar. If you could provide a smaller version of your project that is cut down somewhat that would be very helpful.

I will close this one and continue tracking the issue with [#130](https://github.com/Avindr/MxM-IssueTracking/issues/130#issuecomment-952790686)

**Closed by Avindr** 2021-11-16 06:13 UTC

**Comment by vabichequer** [comment] 2021-11-16 15:04
Hi! So I've just encountered this problem in my code, also. I'm coding a custom trajectory generator and this is what I get:
![image](https://user-images.githubusercontent.com/8205298/142009930-2a59e994-289e-4c5d-8ed5-fa14bd580a37.png)

I've tried messing with the 'TrajectoryBlending' attribute in the MxMAnimator, but no dice. I've recorded 5 minutes of walking motion in a full suit also and no luck. The dataset I'm currently using is the one from Mixamo, provided in the demo scene. Any idea what is happening?

Cheers!

**Comment by Avindr** [comment] 2021-11-17 04:59
> Hi! So I've just encountered this problem in my code, also. I'm coding a custom trajectory generator and this is what I get: ![image](https://user-images.githubusercontent.com/8205298/142009930-2a59e994-289e-4c5d-8ed5-fa14bd580a37.png)
> 
> I've tried messing with the 'TrajectoryBlending' attribute in the MxMAnimator, but no dice. I've recorded 5 minutes of walking motion in a full suit also and no luck. The dataset I'm currently using is the one from Mixamo, provided in the demo scene. Any idea what is happening?
> 
> Cheers!

Hard to tell just seeing screenshot but It doesn't appear to be the same issue. This particular issue doesn't stop the character moving altogether but rather causes the character to get stuck (usually when changing direction) until input is changed again. 

Not sure why your mocap wouldn't work, I'd have to see it to figure out what's up. As far as Mixamo goes, does it have transition animations? I find Mixamo is pretty terrible at best. If there is no walk forward start then the behavior makes sense and I would expect it to do just that. 

Also if you haven't already, I recommend checking out the tutorial videos and documentation for setting up cut clips as there are some nuances to it. 

Let me know what animations you actually have in detail. No need to continue on this thread though, you can either make a new one or PM me on Discord. 

Cheers.

**Comment by LudiKha** [comment] 2022-11-05 11:40
@vabichequer @tadilj in case you might still need a solution:

I've also had this happen to me, and I have reason to believe it's to do with "Next pose tolerance test", which can lead to a host of failures to find matches when configured in a certain way. See this post for more info:

https://github.com/Avindr/MxM-IssueTracking/issues/130#issuecomment-1304330600
