### ISSUE TITLE
Deleting composite always deletes last item in list

### ISSUE THREAD

**Issue by LudiKha** [Avindr/MxM-IssueTracking#59] opened 2020-08-23 12:01 UTC
When deleting a composite (in both Module & Preprossesor), it always deletes the last item in the list.

This is caused by the fact that by the time the warning dialog is interacted with, the variable 'm_currentCompositeCategory' will be iterated to the last element.

Reproduce:

1. Have 2 or more composites in a preprocessor or module
2. Delete an element (not the last)
3. You'll find that the last element gets deleted

**Comment by Avindr** [comment] 2020-08-25 06:20
Hi, Thanks for reporting. 

I wasn't able to reproduce this actually. What version of Unity is this occurring in? Cheers

**Comment by Avindr** [comment] 2020-08-25 06:24
Accidentally clicked the 'closed button on this'. Re-opening because I still need to investigate further.

**Comment by LudiKha** [comment] 2020-08-25 09:01
> Hi, Thanks for reporting.
> 
> I wasn't able to reproduce this actually. What version of Unity is this occurring in? Cheers

That's peculiar. It's in 2020.1.3f1. I do have Sirenix Odin Inspector installed, and the latest UI Toolkit - which might impact the order there. Otherwise I haven't touched those editor classes that cause those issues to me.

**Comment by Avindr** [comment] 2020-09-03 01:22
I think I know what is happening here. Unity in their divine wisdom has decided to change dialog boxes to run in parralel... breaking everyone's implementations. 

It seems to be popping up in a number of places so none are safe in MxM at the moment. I'll see what I can do about this.

**Comment by Avindr** [comment] 2020-09-03 04:01
Actually, I've done some additional testing of this in Unity 2020.1.4f1 and I'm still not able to reproduce it. 

I can't really speak much for Odin as I don't have it. I don't know how it works and not sure why it would affect my custom inspectors. 

Regarding the 'latest UI Toolkit' what is this referring to?

**Comment by LudiKha** [comment] 2020-09-13 09:49
Sorry for the late reply here! 

Very strange that you're not able to reproduce this issue, I'll be doing more animation development next month so I might be able to pinpoint the exact issue then.

As for the latest UI Toolkit, I mean I have com.unity.ui installed as a package, though I don't see how that should change editor UI. I'll keep you updated with my findings...

**Comment by Keiishkii** [comment] 2021-02-24 10:38
Just some info to maybe help fix this, I'm using Unity 2020.1.11.f1, the version of MxM is 2.2.8.

![image](https://user-images.githubusercontent.com/25640783/108988240-239e2d80-768c-11eb-9d4f-72e3ca02392f.png)

This is a video of me reproducing the issue, this happens with my current pre-processor and a newly created one. Let me know if there's anything else I can get you that might help.

https://youtu.be/TIu7B7UBPs8

**Comment by Avindr** [comment] 2021-06-29 02:42
Following additional testing in several LTS versions of Unity (in particular 2020.3LTS) and the latest Unity 2021.1.12f1 build, I am still unable to reproduce this issue with an existing or new anim module or pre-processor. 

I will be closing this issue as I believe that this is likely a Unity error relating to specific Unity versions. If you are still having this issue I recommend updating to LTS or at least the latest available Unity version within your minor version.

**Closed by Avindr** 2021-06-29 02:42 UTC
Labels: Cannot Reproduce, bug
