### ISSUE TITLE
BlendInController(...) doesn't work at "MxM:2.2.5"

### ISSUE THREAD

**Issue by tadilj** [Avindr/MxM-IssueTracking#51] opened 2020-08-11 23:59 UTC
Unity Version: 2019.4.6
MxM Version: MxM v2.2.5
What is happenening?:　BlendInController(...)" which worked until "MxM v2.2.4" does not work after updating to "MxM v2.2.5".
When does it happen?:　An issue with calling BlendInController(...) from the component's UnityEvent().
Can it be easily reproduced? If so how?: Versioning down from "MxM:2.2.5" to "MxM:2.2.4" eliminates the problem.

**Comment by Avindr** [comment] 2020-08-12 00:01
Thanks for the info. I will hotfix this as soon as possible

**Comment by Avindr** [comment] 2020-08-12 00:17
This has now been fixed and will be deployed in a hotfix shortly on the Discord and Unity Asset Store.

**Comment by tadilj** [comment] 2020-08-12 00:51
Thank you HotFix.
I downloaded it as soon as possible, but very unfortunately the problem has not been cured.

**Comment by Avindr** [comment] 2020-08-12 00:59
I just tested it again and it appears to be working on my end. I'm wondering if you might have been too quick on downloading the package and somehow got the old one.

If you open up MxMAnimator_Layers.cs and look at the following line:
![image](https://user-images.githubusercontent.com/29056263/89963345-bd6f3180-dc8a-11ea-89a5-a790998e888b.png

If the highlighted section is not like this then you haven't got the Hotfix. Please confirm

**Comment by Avindr** [comment] 2020-08-12 01:03
Note that the hotfix isn't updated on the Unity Asset Store yet as it still needs to be approved by Unity. 

Currently on the version available on Discord has been updated.

**Comment by Avindr** [comment] 2020-08-17 04:49
I have reverted a change from a previous update to try fix this. I believe it is only an issue in Unity 2019 + versions as it works as intended in the development version of Unity.

Before I upload another Hotfix and close this issue, could you please confirm it works in your project. Open up 'MxMAnimator.cs' 
and comment out the highlighted line shown in the image below:

![image](https://user-images.githubusercontent.com/29056263/90358176-a2405f80-e098-11ea-8ac4-c65a850b9df9.png)

**Comment by transat** [comment] 2020-08-17 06:56
In my case that's fixed the issue.

**Comment by Avindr** [comment] 2020-08-18 00:09
Thanks for checking that for me. I will include this change in the next update.

**Closed by Avindr** 2020-08-18 00:09 UTC
Labels: bug
