### ISSUE TITLE
'ArgumentNullException: Value cannot be null. Parameter name: The Playable is null', during the attempt to create a new Animation Mixer.

### ISSUE THREAD

**Issue by p8rivier** [Avindr/MxM-IssueTracking#152] opened 2022-01-19 17:58 UTC
Hello,

When I try to follow the video 'Blend Space Layers', after follow the different step, when a new Animation mixer should appear, firslty, it doesn't appear and there is this error message :

ArgumentNullException: Value cannot be null.
Parameter name: The Playable is null.
UnityEngine.Playables.PlayableHandle.SetSpeed (System.Double value) (at <02aa3adbfdb645669ebcf8738577b239>:0)
UnityEngine.Playables.PlayableExtensions.SetSpeed[U] (U playable, System.Double value) (at <02aa3adbfdb645669ebcf8738577b239>:0)
MxM.MxMLayer.set_PlaybackSpeed (System.Single value) (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMLayer.cs:55)
MxM.MxMLayer..ctor (System.Int32 a_id, System.Int32 a_maxClips, UnityEngine.Animations.AnimationLayerMixerPlayable& a_layerMixer, UnityEngine.Playables.Playable a_playable, UnityEngine.AvatarMask a_mask, System.Single a_weight, System.Boolean a_additive, System.Boolean a_applyFootIk, System.Single a_playbackSpeed) (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMLayer.cs:242)
MxM.MxMAnimator.AddLayer (UnityEngine.Playables.Playable a_playable, System.Single a_weight, System.Boolean a_additive, UnityEngine.AvatarMask a_mask, System.Boolean a_applyFootIK, System.Boolean a_beforeController, System.Int32 a_maxClips) (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator_Layers.cs:426)
MxM.MxMBlendSpaceLayers.AddBlendSpace (MxM.MxMBlendSpace a_blendSpace) (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/Components/Extensions/MxMBlendSpaceLayers.cs:81)
MxM.MxMBlendSpaceLayers.Initialize () (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/Components/Extensions/MxMBlendSpaceLayers.cs:68)
MxM.MxMAnimator.SetupExtensions () (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator.cs:1100)
MxM.MxMAnimator.Initialize () (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator.cs:859)
MxM.MxMAnimator.Start () (at Assets/Plugins/MotionMatching/Code/MxM/Runtime/MxMAnimator/MxMAnimator.cs:370)

Thanks in advance!

**Comment by Avindr** [comment] 2022-01-31 05:17
Thanks for the info, I will investigate the cause and fix it for the next update.

**Comment by Avindr** [comment] 2022-02-09 04:18
This has been fixed and will be included with the next update.

**Closed by Avindr** 2022-02-09 04:18 UTC
Labels: bug

**Comment by Avindr** [comment] 2022-02-09 04:26
Here's a quick patch in the meantime.

[MxMLayerPatch.zip](https://github.com/Avindr/MxM-IssueTracking/files/8029359/MxMLayerPatch.zip)
